---
- name: Install packages needed to use the Kubernetes apt repository
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Download the public signing key for the Kubernetes package repositories
  apt_key:
    # The same signing key is used for all repositories, so you can disregard the version in the URL
    url: https://pkgs.k8s.io/core:/stable:/{{ kube_repo_version }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add kubernetes repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kube_repo_version }}/deb/ /"
    filename: kubernetes
    state: present
    update_cache: yes

- name: Install kubernetes packages
  apt:
    pkg:
      - kubelet={{ kube_version }}*
      - kubeadm={{ kube_version }}*
      - kubectl={{ kube_version }}*
  when: kube_version != "latest"

- name: Install kubernetes packages
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
  when: kube_version == "latest"

- name: remove mlocate
  apt:
    pkg:
      - mlocate
    state: absent
