---
- name: Create directory /var/lib/etcd
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755

- name: Move ETCD in RAM
  mount:
    path: /var/lib/etcd
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,size=2g
    state: mounted
