---
- name: Install NERDCTL
  unarchive: 
    src: https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create a directories if not exist
  block:
  - name: Create a directory for binaries
    file:
      path: /opt/etcdRAM/bin/
      state: directory
      mode: '0755'
  - name: Create a directory for backup
    file:
      path: /var/lib/etcdRAM/etcd/
      state: directory
      mode: '0755'

- name: Copy files for etcdRAM
  block:
  # - name: Copy cronjob file
  #   copy:
  #     src: files/files_etcdRAM/etc/cron.d/etcdRAM-etcd
  #     dest: /etc/cron.d/etcdRAM-etcd
  #     mode: '0644'
  - name: Copy scripts
    copy:
      src: files/files_etcdRAM/opt/etcdRAM/bin/
      dest: /opt/etcdRAM/bin/
      mode: '0755'
  - name: Copy kubelet configuration
    copy:
      src: files/files_etcdRAM/usr/lib/systemd/system/kubelet.service.d/
      dest: /usr/lib/systemd/system/kubelet.service.d/
      mode: '0644'
    notify: restart daemon-reload

# - name: Add a cron file from dir /etc/cron.d
#   ansible.builtin.shell: "crontab /etc/cron.d/etcdRAM-etcd"

# - name: Install crontab
#   ansible.builtin.package:
#     name: crontab
#     state: present

- name: Running periodic jobs
  block:
  - name: Run etcd-cron job
    ansible.builtin.cron:
      name: "Run the job every 20 minutes"
      minute: "*/20"
      user: root
      job: "/opt/etcdRAM/bin/etcd-cron > /var/log/etcdRAM-etcd-backup 2>&1"
      cron_file: etcdRAM-etcd
  - name: Run the job once a day
    ansible.builtin.cron:
      name: "Run etcdctl job"
      minute: "30"
      hour: "0"
      user: root
      job: "/opt/etcdRAM/bin/etcdctl defrag --cluster > /var/log/etcdRAM-etcd-defrag 2>&1"
      cron_file: etcdRAM-etcd
