---
- name: Set Ansible Galaxy GPU Support Role name fact
  ansible.builtin.set_fact:
    gpu_support_role_name: "{{ gpu_support_role.split('/') | last }}"

- name: Print Ansible Galaxy GPU Support Role facts
  ansible.builtin.debug:
    msg: "gpu_support_role: {{ gpu_support_role }}, gpu_support_role_name: {{ gpu_support_role_name }}"

- name: Install Ansible Galaxy GPU Support Role on Control node
  delegate_to: 127.0.0.1
  ansible.builtin.command: ansible-galaxy install -f -i -c {{ gpu_support_role }}
  register: gpu_support_role_install
  changed_when: >
    gpu_support_role_install.rc == 0 and
    ('is already installed, skipping' not in gpu_support_role_install.stdout)

- name: Include Ansible Galaxy GPU Support Role
  ansible.builtin.include_role:
    # name: ansible-role-gpu-support
    name: "{{ gpu_support_role_name }}"
  vars:
    node_type: "{{ (kube_type_of_node == 'wn') | ternary('worker', 'master') }}"
    node_cluster_type: "kubernetes"
