---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Include debug info tasks
  ansible.builtin.include_tasks: debug-info.yaml

- name: Include tasks for OS family {{ ansible_os_family }}
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yaml"

- name: Install Nvidia stuff
  ansible.builtin.include_tasks: nvidia.yaml
  when: (use_gpu | default(false) | bool)

- name: Include tasks for node type {{ kube_type_of_node }}
  ansible.builtin.include_tasks: "{{ kube_type_of_node }}.yaml"

# - name: Include "{{kube_type_of_node}}" tasks
#   include: "{{kube_type_of_node}}.yaml"
