---

- name: Include tasks for node type {{ kube_type_of_node }}
  ansible.builtin.include_tasks: "{{ kube_type_of_node }}.yaml"

- name: Add GPU support for node type {{ kube_type_of_node }}
  ansible.builtin.include_tasks: gpu-support.yaml
  when: (enable_gpu | default(false) | bool)
