---
- name: Get hostname and set node label
  when: nodelabel != ""
  block:
  - name: Get hostname
    ansible.builtin.command: hostname
    register: hostname
    changed_when: false
  - name: Set node Label
    ansible.builtin.command: kubectl label node {{ IM_NODE_HOSTNAME }} {{ nodelabel }}
    environment:
      KUBECONFIG: /etc/rancher/rke2/rke2.yaml
    delegate_to: "{{ kube_front_end_ip }}"
