- name: sysctl-system
  command: sysctl --system

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: restart daemon-reload
  systemd:
    daemon_reload: yes

- name: restart containerd
  service:
    name: containerd
    state: restarted
