apiVersion: cert-manager.io/v1
kind: ClusterIssuer
{% if cert_manager_type == 'self-signed' %}
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{% else %}
metadata:
  name: {{ cluster_issuer_name }}
spec:
  acme:
    # The ACME server URL
    server: {{ acme_server_url }}
    # Email address used for ACME registration
    email: {{ acme_email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{% endif %}  
