apiVersion: cert-manager.io/v1
kind: ClusterIssuer
{% if cert_manager_type == 'self-signed' %}
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{% else %}
metadata:
  name: "{{ cluster_issuer_name }}"
spec:
  acme:
    server: "{{ acme_server_url }}"
    email: "{{ acme_email }}"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{% endif %}  
