grafana:
  adminPassword: "{{ admin_token }}"
  persistence:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: {{ cluster_issuer_name }}
  hosts:
  - "grafana.{{ dns_name }}"
  tls:
  - hosts:
    - "grafana.{{ dns_name }}"
    secretName: grafana-secret

prometheus:
  ingress:
    enabled: false

alertmanager:
  enabled: false